# Generated by Django 4.1.7 on 2023-02-25 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phoneNumber", models.IntegerField(verbose_name=20)),
                ("email", models.CharField(max_length=50)),
                ("about", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=30)),
                ("language", models.CharField(max_length=30)),
                (
                    "profilePicture",
                    models.ImageField(blank=True, upload_to="profile_images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("postID", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("postContent", models.CharField(max_length=1000)),
                ("postImage", models.ImageField(blank=True, upload_to="images")),
                ("postDate", models.DateTimeField()),
                ("postLikes", models.IntegerField(max_length=999)),
                (
                    "postBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ImSick.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("commentID", models.AutoField(primary_key=True, serialize=False)),
                ("commentDate", models.DateTimeField()),
                ("commentContent", models.CharField(max_length=50)),
                (
                    "commentOnPost",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ImSick.post",
                    ),
                ),
                (
                    "commentedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ImSick.useraccount",
                    ),
                ),
            ],
        ),
    ]
