# Generated by Django 4.1.7 on 2023-02-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImSick", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="postLikes",
            field=models.IntegerField(verbose_name=999),
        ),
    ]
